source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@stash.odkl.ru:7999/ios/podspecs.git'

use_modular_headers!
use_frameworks!
inhibit_all_warnings!

platform :ios, '12.0'

def sharedPods
  pod 'SwiftLint'

# Development pods

  pod 'ResolverProtocol', :path => '../../ResolverProtocol/'
  pod 'Resolver', :path => '../../Resolver/'
end

target 'Example' do
  sharedPods
end

target 'ExampleTests' do
  sharedPods

  pod 'Quick', '5.0.1'
  pod 'Nimble', '10.0.0'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
